#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/reactor .
docker build -t ${REPO}/reactor:${TAG} .

echo Built ${REPO}/reactor:${TAG}
